import { Project, ProjectStatus, ThemeArea } from './types';

export const initialProjects: Project[] = [
  {
    id: 'Proj-018',
    entityName: 'INSTITUTO TRANSFORMA',
    cnpj: '43.468.154/0001-15',
    municipality: 'Mogi das Cruzes',
    projectName: 'Esporte e Cultura Transforma',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Atividades de ballet, dança, ginástica rítmica, muay thai, judô, futebol, basquete, vôlei, circo e teatro voltadas a crianças e adolescentes do Jardim Lagoa Seca. Objetivo de promover desenvolvimento integral e afastar crianças da vulnerabilidade.',
    beneficiaries: '200 crianças e adolescentes (direto), 1000 indiretos',
    requestedValue: 300000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 100,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Oficinas de esporte para criancasProjeto ja em pratica ha alguns anos, com otima aceitacao da populacao alvo, muito bem elaborado e documentado, envolve esporte, educacao, cultura. Popul alvo 200 criancas e suas familias - verificado lla',
    evaluation: { history: 20, consistency: 30, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-025',
    entityName: 'Fundo Municipal de Cultura',
    cnpj: '62.378.011/0001-67',
    municipality: 'Hortolandia',
    projectName: 'Música que Transforma – Nova Banda Jovem',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Fortalecimento estrutural e visual da Nova Banda Jovem de Hortolândia. Aquisição de equipamentos e uniformes para 40 jovens em vulnerabilidade.',
    beneficiaries: '40 jovens músicos e comunidade (30 mil pessoas)',
    requestedValue: 200000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 85,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Orquestra jovem. Ja em andamento desde 2023, 40 jovens musicos. Ja tocaram com artistas conhecidos. Orcamento visa principalmente troca instrumentos e aparelhos som, custos de funcionamento nao contemplados',
    evaluation: { history: 20, consistency: 15, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-029',
    entityName: 'GRUPO CULTURAL AMIGOS',
    cnpj: '02.864.682/0001-06',
    municipality: 'Serrana',
    projectName: 'Projeto Agir & Progredir',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Projeto social esportivo com Jiu-Jitsu, Skate, Vôlei e Funcional para mulheres e crianças em região de vulnerabilidade. Inclui atendimento psicológico.',
    beneficiaries: '120 pessoas (crianças e mulheres idosas)',
    requestedValue: 218500,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 70,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Aulas volei, funcional para idosos+ psicologos. Inicio do projeto<2 anos (fev/24). Nao ha descricao clara de objetivos e de como verificarao resultados. Orcamento visa custeio de salarios de professores e festas.',
    evaluation: { history: 10, consistency: 15, budget: 20, mandateRelation: 5, socialImpact: 20 }
  },
  {
    id: 'Proj-033',
    entityName: 'Associação Instituto Cultural Arte e Dança e Movimento de Niteroi',
    cnpj: '51.579.106/0001-22',
    municipality: 'Niterói RJ',
    projectName: 'Assocaição Instituto Cultural Dança Arte e Movimento',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Aulas regulares, oficinas, palestras e apresentações públicas de dança. Resgate da cidadania e formação cultural.',
    beneficiaries: '150 a 300 pessoas',
    requestedValue: 294508,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.REJECTED,
    score: 30,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Nao atua em Sao Paulo. Nao consegui acessar documentos anexados. Nao encontrei instagram ou outra referencia em redes sociais',
    evaluation: { history: 0, consistency: 0, budget: 0, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-038',
    entityName: 'Associação esportiva cultural e Educacional Abraço Campeão',
    cnpj: '28.218.528/0001-50',
    municipality: 'Rio de Janeiro',
    projectName: 'Complexo do Alemão Abraçando Campeões',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Atividades de Boxe e Artes Marciais aliadas a educação alternativa e desenvolvimento pessoal no Complexo do Alemão.',
    beneficiaries: '240 vagas para crianças e jovens',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.REJECTED,
    score: 70,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Nao atua em Sao paulo. Projeto consistente, ja em execucao com resultados importantes de impacto social. Cronograma pouco detalhado',
    evaluation: { history: 0, consistency: 30, budget: 10, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-040',
    entityName: 'Prefeitura Municipal de Estiva Gerbi',
    cnpj: '67.168.856/0001-41',
    municipality: 'Estiva Gerbi',
    projectName: 'Trilhos da Memória',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Container Cultural para resgatar a história ferroviária e fortalecer a identidade cultural do município.',
    beneficiaries: 'População local e turistas',
    requestedValue: 205000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.REJECTED,
    score: 65,
    evaluator: 'Adriano Moreira de Andrade',
    feedback: 'Projeto da prefeitura para divulgar história da cidade e da ferrovia. Pouco impacto social a curto e longo prazo',
    evaluation: { history: 0, consistency: 30, budget: 20, mandateRelation: 5, socialImpact: 10 }
  },
  {
    id: 'Proj-045',
    entityName: 'Reflexões da Liberdade',
    cnpj: '29.631.275/0001-05',
    municipality: 'Embu das Artes',
    projectName: 'Despertar para a Liberdade nas Prisões',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Oficinas de autoconhecimento, empatia e propósito de vida para pessoas privadas de liberdade.',
    beneficiaries: '1200 pessoas privadas de liberdade',
    requestedValue: 450000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 85,
    evaluator: 'Adriano Moreira de Andrade',
    feedback: 'O projeto é consistente, porém, seria salutar separar os recursos que seriam destinados à Equipe técnica do que seriam destinados à coordenação geral.',
    evaluation: { history: 20, consistency: 15, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-046',
    entityName: 'Associação dos Cegos de Ribeirão Preto',
    cnpj: '56.021.652/0001-67',
    municipality: 'Ribeirão Preto',
    projectName: 'Serviço de Acolhimento Institucional',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Acolhimento provisório de pessoas adultas com deficiência visual, visando autonomia e reintegração.',
    beneficiaries: '10 usuários diretos (acolhimento)',
    requestedValue: 437220,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.UNDER_REVIEW,
    score: 0,
    evaluator: 'Adriano Moreira de Andrade',
    feedback: 'Parece estar em dificuldades nos últimos tempos. Restrigindo-se apenas a distribuir algumas cestas básicas. Necessita diligência.',
    evaluation: { history: 20, consistency: 0, budget: 0, mandateRelation: 10, socialImpact: 0 }
  },
  {
    id: 'Proj-047',
    entityName: 'INSTITUTO FEDERAL DE SÃO PAULO - Campus SÃO ROQUE',
    cnpj: '10.882.594/0006-70',
    municipality: 'São Roque',
    projectName: 'REFORMA GINÁSIO POLIESPORTIVO DO CAMPUS SÃO ROQUE',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Reforma e modernização do ginásio (pintura, piso, alambrados, elétrica) para garantir segurança e funcionalidade.',
    beneficiaries: '1.200 estudantes e comunidade local',
    requestedValue: 235000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 75,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Reforma de centro esportivo. Orcamento obra < 400000. Nao envolve ampliacao, apenas reforma. (Duplicidade tratada)',
    evaluation: { history: 20, consistency: 30, budget: 10, mandateRelation: 5, socialImpact: 10 }
  },
  {
    id: 'Proj-050',
    entityName: 'INDESC',
    cnpj: '07.393.987/0001-09',
    municipality: 'Jundiaí',
    projectName: 'Cozinhas Solidárias Sobre Rodas',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Aquisição de veículo para ampliar a capacidade logística das 15 cozinhas solidárias geridas pelo INDESC.',
    beneficiaries: 'Milhares em vulnerabilidade alimentar',
    requestedValue: 350000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.PENDING,
    score: 0,
    evaluator: '', // Será atribuído logicamente à Tabata Amaral no App.tsx
    feedback: '',
    evaluation: { history: 0, consistency: 0, budget: 0, mandateRelation: 0, socialImpact: 0 }
  },
  {
    id: 'Proj-052',
    entityName: 'Casa do Pequeno Cidadão',
    cnpj: '04.436.297/0001-93',
    municipality: 'São Paulo',
    projectName: 'Cuidoteca',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Implementar um espaço público, gratuito e seguro de cuidado para crianças de 3 a 12 anos com deficiência.',
    beneficiaries: '100 crianças e 100 famílias',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 100,
    evaluator: 'Adriano Moreira de Andrade',
    feedback: 'Projeto e orcamento detalhados. Organizacao antiga e forte. Atende demanda crucial de mães atípicas.',
    evaluation: { history: 20, consistency: 30, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-053',
    entityName: 'Associação Cultural Yacamim',
    cnpj: '25.157.245/0001-58',
    municipality: 'Santa Isabel',
    projectName: 'YACAMIM TERRITÓRIO CRIATIVO',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Oficinas gratuitas de música, artes visuais e artesanato. Realização de mostra cultural.',
    beneficiaries: '120 participantes diretos',
    requestedValue: 260000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 100,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Oficinas musica e artesanato. Projeto em andamento, bem desenvolvido. Amplamente relatado em redes sociais. Orcamento ok',
    evaluation: { history: 20, consistency: 30, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-060',
    entityName: 'Associação EternamenteSou',
    cnpj: '31.154.112/0001-20',
    municipality: 'São Paulo',
    projectName: 'Promoção Saúde LGBT+ Idosa',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Promoção da integração e melhoria na qualidade de vida da população LGBT+ em suas velhices.',
    beneficiaries: '300 pessoas idosas LGBT+',
    requestedValue: 483400,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 95,
    evaluator: 'Mariana Costa',
    feedback: 'Projeto único e necessário. Orçamento detalhado e instituição com reconhecimento internacional.',
    evaluation: { history: 20, consistency: 30, budget: 15, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-251',
    entityName: 'Prefeitura de Sorocaba',
    cnpj: '46.634.044/0001-74',
    municipality: 'Sorocaba',
    projectName: 'Desenvolve Sorocaba',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Capacitação prática, mentoria e apoio técnico a microempreendedores e empresas de pequeno porte.',
    beneficiaries: '340 empreendedores',
    requestedValue: 477000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 90,
    evaluator: 'Pedro Santos',
    feedback: 'Forte alinhamento com pauta de desenvolvimento econômico. Parceria com Sebrae garante qualidade.',
    evaluation: { history: 20, consistency: 30, budget: 20, mandateRelation: 10, socialImpact: 10 }
  },
  {
    id: 'Proj-302',
    entityName: 'Instituto Jô Clemente',
    cnpj: '60.502.242/0001-05',
    municipality: 'São Paulo',
    projectName: 'IA e Inclusão no Trabalho',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Fortalecer a inclusão laboral de pessoas com deficiência intelectual e TEA em cenário de IA.',
    beneficiaries: '540 pessoas com deficiência',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.PENDING,
    score: 0,
    evaluator: '', // Será atribuído logicamente à Tabata Amaral no App.tsx
    feedback: '',
    evaluation: { history: 0, consistency: 0, budget: 0, mandateRelation: 0, socialImpact: 0 }
  },
  {
    id: 'Proj-615',
    entityName: 'ASSOCIAÇÃO PAULISTA DE ESPORTE E CULTURA',
    cnpj: '29.663.413/0001-38',
    municipality: 'Paraguaçu Paulista',
    projectName: 'NÚCLEO DE FORMAÇÃO DE ATLETAS DE BASQUETEBOL',
    theme: ThemeArea.CULTURE_SPORT,
    description: 'Formação de atletas de basquetebol de alto rendimento e formação cidadã. Contratação de profissionais e materiais.',
    beneficiaries: '60 atletas diretos, 300 indiretos',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 80,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Basquetebol jovens - projeto e orcamento bem detalhados, achei valor um pouco alto. Nao encontrei nada nas redes sobre a associacao.',
    evaluation: { history: 10, consistency: 30, budget: 10, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-785',
    entityName: 'Centro Integração Empresa Escola - CIEE',
    cnpj: '61.600.839/0001-55',
    municipality: 'São Paulo',
    projectName: 'Oficinas de Criatividade',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Preparação de jovens para o mundo do trabalho (currículo, postura, autoconhecimento).',
    beneficiaries: '600 jovens',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 80,
    evaluator: 'Adriana dias dos anjos',
    feedback: 'Oficinas de criatividade para jovens- custo alto para poucas horas de aulas por aluno, o q acarreta impacto menor.',
    evaluation: { history: 20, consistency: 30, budget: 10, mandateRelation: 10, socialImpact: 10 }
  },
  {
    id: 'Proj-799',
    entityName: 'Associação Assistencial Projeto Corrente do Bem',
    cnpj: '38.972.138/0001-25',
    municipality: 'Presidente Prudente',
    projectName: 'Protagonistas 60+',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Oficinas socioeducativas, culturais e corporais para idosos. Convivência e fortalecimento de vínculos.',
    beneficiaries: '30 idosos',
    requestedValue: 300000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 80,
    evaluator: 'Mariana Costa',
    feedback: 'Atividades para 30 idosos',
    evaluation: { history: 20, consistency: 30, budget: 10, mandateRelation: 10, socialImpact: 10 }
  },
  {
    id: 'Proj-801',
    entityName: 'Fundação Dorina Nowill para Cegos',
    cnpj: '60.507.100/0001-30',
    municipality: 'São Paulo',
    projectName: 'Ler sem Barreiras',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Modernização da Biblioteca, tecnologias assistivas e Núcleo de Difusão do Conhecimento.',
    beneficiaries: '3.000 beneficiários',
    requestedValue: 254879,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 100,
    evaluator: 'Pedro Santos',
    feedback: 'Modernizacao biblioteca para cegos/ projeto e orcamento detalhados',
    evaluation: { history: 20, consistency: 30, budget: 20, mandateRelation: 10, socialImpact: 20 }
  },
  {
    id: 'Proj-805',
    entityName: 'Associação de Amparo a Moradia Clínica da Alma',
    cnpj: '08.628.417/0001-05',
    municipality: 'Itanhaém',
    projectName: 'Infraestrutura Essencial e Segurança',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Aquisição de veículo, armários inox, cadeiras de banho e custeio para ILPI em zona rural.',
    beneficiaries: 'Idosos residentes',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 75,
    evaluator: 'Mariana Costa',
    feedback: 'Casa de idosos- compra de veiculo+custos de funcionamento da casa. Nao consegui descobrir a populacao atingida, mas aparenta se tratar de 15 a 20 idosos.Orcamento um tanto elevado',
    evaluation: { history: 20, consistency: 15, budget: 10, mandateRelation: 10, socialImpact: 20 }
  }
];