import { Project, ProjectStatus, ThemeArea } from './types';

// Data extracted from PDF OCR and fully evaluated by JSSobrinho
export const initialProjects: Project[] = [
  {
    id: 'Proj-178',
    entityName: 'DEPARTAMENTO DE CULTURA E TURISMO',
    cnpj: '45.159.381/0001-94',
    municipality: 'Urupês',
    projectName: 'Raízes Criativas - Cult',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Promover o empoderamento através da arte. Coordenação e arte no espaço público Casa da Cultura.',
    beneficiaries: 'Jovens e adultos da comunidade local',
    requestedValue: 210000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 82,
    evaluator: 'JSSobrinho',
    feedback: 'Projeto consistente com forte apelo cultural e comunitário.',
    evaluation: { history: 15, consistency: 25, mandateRelation: 8, socialImpact: 18, budget: 16 }
  },
  {
    id: 'Proj-181',
    entityName: 'PREFEITURA MUNICIPAL DE JUQUITIBA',
    cnpj: '46.634.440/0001-00',
    municipality: 'Juquitiba',
    projectName: 'Mãe Juquitibense',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Oferecer consultoria e suporte à gestação. Atendimento físico em uma consultoria especializada para 330 mães.',
    beneficiaries: '330 mães grávidas e 330 bebês',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 92,
    evaluator: 'JSSobrinho',
    feedback: 'Excelente iniciativa de saúde preventiva e suporte materno. Alto impacto social.',
    evaluation: { history: 18, consistency: 28, mandateRelation: 10, socialImpact: 20, budget: 16 }
  },
  {
    id: 'Proj-183',
    entityName: 'PREFEITURA MUNICIPAL DE TAUBATÉ',
    cnpj: '45.176.005/0001-08',
    municipality: 'Taubaté',
    projectName: 'Passarela da Vida',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Considerando a importância do desenvolvimento urbano, o projeto visa a construção/reforma de passarela para segurança de pedestres.',
    beneficiaries: 'População local que utiliza a travessia',
    requestedValue: 200816,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 75,
    evaluator: 'JSSobrinho',
    feedback: 'Projeto de infraestrutura importante, embora fuja um pouco do foco principal de inovação, garante segurança.',
    evaluation: { history: 15, consistency: 20, mandateRelation: 5, socialImpact: 20, budget: 15 }
  },
  {
    id: 'Proj-186',
    entityName: 'PREFEITURA MUNICIPAL DE TAUBATÉ',
    cnpj: '45.176.005/0001-08',
    municipality: 'Taubaté',
    projectName: 'Aquisição de uma Pic',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Aquisição de veículo (Van/Pick-up) para transporte de pacientes ou assistência social, melhorando a logística da saúde.',
    beneficiaries: 'Usuários do sistema de saúde/social',
    requestedValue: 484534,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 78,
    evaluator: 'JSSobrinho',
    feedback: 'Aquisição de bens duráveis com justificativa clara de uso para saúde.',
    evaluation: { history: 15, consistency: 25, mandateRelation: 6, socialImpact: 18, budget: 14 }
  },
  {
    id: 'Proj-189',
    entityName: 'PREFEITURA MUNICIPAL DE ITU',
    cnpj: '46.634.440/0001-00',
    municipality: 'Itu',
    projectName: 'CONSTRUÇÃO DE CENTRO (CRAS V)',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Construção de prédio para o CRAS V - Recriança. Objetivo de ampliar o atendimento social em área vulnerável.',
    beneficiaries: '5.000 famílias em vulnerabilidade',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 95,
    evaluator: 'JSSobrinho',
    feedback: 'Investimento estrutural de alto impacto e perenidade. Alinhado com fortalecimento do SUAS.',
    evaluation: { history: 20, consistency: 30, mandateRelation: 8, socialImpact: 20, budget: 17 }
  },
  {
    id: 'Proj-191',
    entityName: 'ASSOCIAÇÃO AMANDO O PRÓXIMO',
    cnpj: '15.585.000/0002-59',
    municipality: 'Cruzeiro',
    projectName: 'LAÇOS QUE TRANSFORMAM',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Projeto de fortalecimento de vínculos no bairro Jardim América. Foco na redução das vulnerabilidades sociais.',
    beneficiaries: '120 crianças e adolescentes',
    requestedValue: 400000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 84,
    evaluator: 'JSSobrinho',
    feedback: 'Boa metodologia de intervenção social. Entidade com histórico local.',
    evaluation: { history: 16, consistency: 24, mandateRelation: 8, socialImpact: 20, budget: 16 }
  },
  {
    id: 'Proj-194',
    entityName: 'ENACTUS BRASIL',
    cnpj: '13.944.860/0001-25',
    municipality: 'São Paulo',
    projectName: 'ENACTUS WORLD CUP',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Ampliar a participação brasileira na conferência global, fomentando o empreendedorismo social universitário.',
    beneficiaries: 'Estudantes universitários e comunidades atendidas',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 88,
    evaluator: 'JSSobrinho',
    feedback: 'Projeto de grande visibilidade e fomento ao empreendedorismo jovem. Excelente consistência.',
    evaluation: { history: 20, consistency: 28, mandateRelation: 10, socialImpact: 15, budget: 15 }
  },
  {
    id: 'Proj-204',
    entityName: 'MUNICÍPIO DE TAUBATÉ',
    cnpj: '45.176.005/0001-08',
    municipality: 'Taubaté',
    projectName: 'Movimenta PSE',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'O projeto prevê a aquisição de veículos para garantir suporte logístico ao Programa Saúde na Escola (PSE).',
    beneficiaries: 'Rede pública de ensino',
    requestedValue: 390000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 80,
    evaluator: 'JSSobrinho',
    feedback: 'Integração Saúde e Educação é prioritária. Orçamento adequado.',
    evaluation: { history: 15, consistency: 25, mandateRelation: 8, socialImpact: 17, budget: 15 }
  },
  {
    id: 'Proj-215',
    entityName: 'Associação Assistencial',
    cnpj: '58.381.435/0001-03',
    municipality: 'Mogi Guaçu',
    projectName: 'Projeto Adolescente',
    theme: ThemeArea.SOCIAL_DEV,
    description: 'Metas estabelecidas para inserção e capacitação de adolescentes, fundada em 21 de fevereiro.',
    beneficiaries: 'Adolescentes em vulnerabilidade',
    requestedValue: 499888,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 81,
    evaluator: 'JSSobrinho',
    feedback: 'Foco na juventude alinhado com o mandato. Valor próximo ao teto, mas justificável pelo alcance.',
    evaluation: { history: 15, consistency: 24, mandateRelation: 9, socialImpact: 18, budget: 15 }
  },
  {
    id: 'Proj-562',
    entityName: 'Tron Editora Ltda',
    cnpj: '62.338.819/0001-10',
    municipality: 'São Paulo',
    projectName: 'A memória dos Bairros',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Projeto prevê a produção de material editorial sobre a história local dos bairros. Empresa com fins lucrativos.',
    beneficiaries: 'Leitores locais',
    requestedValue: 500000,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.REJECTED,
    score: 45,
    evaluator: 'JSSobrinho',
    feedback: 'Proponente é empresa Ltda, o que pode gerar vedação legal para emenda direta. Baixo impacto social direto comparado aos demais.',
    evaluation: { history: 5, consistency: 15, mandateRelation: 5, socialImpact: 5, budget: 15 }
  },
  {
    id: 'Proj-590',
    entityName: 'FEDERACAO DAS EMPRESAS JUNIORES',
    cnpj: '64.049.224/0001-70',
    municipality: 'Campinas',
    projectName: 'Transforme SP',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Apoio a 50 empresas juniores desde a pandemia. Fomento ao ecossistema empreendedor universitário.',
    beneficiaries: '50 Empresas Juniores e seus membros',
    requestedValue: 261100,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 90,
    evaluator: 'JSSobrinho',
    feedback: 'Alta sinergia com pauta de inovação e educação. Custo-benefício excelente.',
    evaluation: { history: 18, consistency: 28, mandateRelation: 10, socialImpact: 16, budget: 18 }
  },
  {
    id: 'Proj-607',
    entityName: 'Instituto de Tecnologia e Sociedade',
    cnpj: '04.782.112/0001-00',
    municipality: 'São Paulo',
    projectName: 'CATÁLOGO NACIONAL',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Garantir a efetividade do catálogo nacional. O ITS Brasil possui know-how tecnológico consolidado.',
    beneficiaries: 'Usuários de serviços digitais',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 86,
    evaluator: 'JSSobrinho',
    feedback: 'Proposta técnica robusta. Organização de referência na área.',
    evaluation: { history: 20, consistency: 25, mandateRelation: 9, socialImpact: 14, budget: 18 }
  },
  {
    id: 'Proj-675',
    entityName: 'Associação Patrulheiros Mirins',
    cnpj: '44.387.959/0001-58',
    municipality: 'São Caetano do Sul',
    projectName: 'Por Dentro do Audiovisual',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Formar adolescentes na área de audiovisual na região do ABC Paulista. Foco em economia criativa.',
    beneficiaries: 'Jovens aprendizes',
    requestedValue: 496196,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 83,
    evaluator: 'JSSobrinho',
    feedback: 'Capacitação técnica para o mercado de trabalho (economia criativa). Muito bom.',
    evaluation: { history: 18, consistency: 24, mandateRelation: 8, socialImpact: 18, budget: 15 }
  },
  {
    id: 'Proj-723',
    entityName: 'Prefeitura Municipal de Itu',
    cnpj: '46.634.440/0001-00',
    municipality: 'Itu',
    projectName: 'Acesso à Empregabilidade',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Projeto na região do Pirapitingui. Meta: Atingir até 100 beneficiários com foco em qualificação profissional.',
    beneficiaries: '100 trabalhadores desempregados',
    requestedValue: 498324,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 88,
    evaluator: 'JSSobrinho',
    feedback: 'Foco direto em geração de renda e emprego. Essencial.',
    evaluation: { history: 15, consistency: 28, mandateRelation: 9, socialImpact: 20, budget: 16 }
  },
  {
    id: 'Proj-731',
    entityName: 'Prefeitura Municipal de Itu',
    cnpj: '46.634.440/0001-00',
    municipality: 'Itu',
    projectName: 'Acesso a Empregabil (Fase 2)',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Expansão do projeto de empregabilidade. Foco em novos bairros e parcerias com empresas locais.',
    beneficiaries: 'Mais 100 beneficiários',
    requestedValue: 498319,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 87,
    evaluator: 'JSSobrinho',
    feedback: 'Continuidade de política pública exitosa.',
    evaluation: { history: 15, consistency: 28, mandateRelation: 9, socialImpact: 19, budget: 16 }
  },
  {
    id: 'Proj-733',
    entityName: 'But Futebol Clube',
    cnpj: '04.450.009/0001-55',
    municipality: 'São Paulo',
    projectName: 'Mães do But Futebol',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'As mulheres do Trem. Projeto formará 60 mulheres. Capacitação profissional e empoderamento feminino.',
    beneficiaries: '60 mulheres',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 85,
    evaluator: 'JSSobrinho',
    feedback: 'Recorte de gênero importante (Mulheres). Aderência total ao mandato.',
    evaluation: { history: 12, consistency: 25, mandateRelation: 10, socialImpact: 20, budget: 18 }
  },
  {
    id: 'Proj-747',
    entityName: 'Prefeitura Municipal de Pirassununga',
    cnpj: '45.731.650/0001-45',
    municipality: 'Pirassununga',
    projectName: 'Programa CECAP',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Espaço do Empreendedor. Ofertar geração de novos negócios e suporte técnico.',
    beneficiaries: 'Empreendedores locais',
    requestedValue: 489401,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 79,
    evaluator: 'JSSobrinho',
    feedback: 'Bom projeto de fomento econômico municipal.',
    evaluation: { history: 15, consistency: 22, mandateRelation: 8, socialImpact: 16, budget: 18 }
  },
  {
    id: 'Proj-763',
    entityName: 'FUNDACAO DE APOIO À TECNOLOGIA',
    cnpj: '68.314.830/0001-27',
    municipality: 'São Paulo',
    projectName: 'Observatório de Transf. Digital',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Plataforma de governança e desenvolvimento científico. Operar o Observatório de Transformação Digital.',
    beneficiaries: 'Setor produtivo e acadêmico',
    requestedValue: 500000,
    hasParliamentaryAmendment: true,
    status: ProjectStatus.APPROVED,
    score: 89,
    evaluator: 'JSSobrinho',
    feedback: 'Projeto de alta complexidade e relevância para inovação tecnológica.',
    evaluation: { history: 20, consistency: 29, mandateRelation: 10, socialImpact: 12, budget: 18 }
  },
  {
    id: 'Proj-769',
    entityName: 'Artesol - Artesanato Solidário',
    cnpj: '05.354.529/0001-27',
    municipality: 'São Paulo',
    projectName: 'Rede Artesanato de SP',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Valorização do artesanato tradicional. Rede Artesol espera atender 30 grupos de artesãos.',
    beneficiaries: '30 artesãos/grupos',
    requestedValue: 262210,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 91,
    evaluator: 'JSSobrinho',
    feedback: 'Economia criativa e preservação cultural. Entidade renomada.',
    evaluation: { history: 20, consistency: 28, mandateRelation: 8, socialImpact: 20, budget: 15 }
  },
  {
    id: 'Proj-773',
    entityName: 'Artesol - Artesanato Solidário',
    cnpj: '05.354.529/0001-27',
    municipality: 'São Paulo',
    projectName: 'Rede Artesanato (Expansão)',
    theme: ThemeArea.ENTREPRENEURSHIP,
    description: 'Continuidade do projeto de rede. Foco na comercialização e design dos produtos artesanais.',
    beneficiaries: 'Novos grupos de artesãos',
    requestedValue: 262210,
    hasParliamentaryAmendment: false,
    status: ProjectStatus.APPROVED,
    score: 89,
    evaluator: 'JSSobrinho',
    feedback: 'Complementar ao projeto anterior, reforçando a estratégia de rede.',
    evaluation: { history: 20, consistency: 27, mandateRelation: 8, socialImpact: 19, budget: 15 }
  }
];